
spring:
  application:
    name: bancopichincha
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update

# Enable Swagger UI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

info:
  app:
    name: Banco Pichincha API
    description: API para la gestión de clientes del Banco Pichincha
    version: 1.0.0